### ISSUE TITLE
[BUG]  No module btrfsutil were found

### ISSUE THREAD

**Issue by vuanhatran** [jrabinow/snapper-rollback#12]
**Describe the bug**
The following packages "btrfs-progs libopenmpt libupnp" after the `paru -Syu` and then the snapper-rollback return error: No module btrfsutil were found

**To Reproduce**
- step 1 Upgrade to the newest version of "btrfs-progs libopenmpt libupnp"
- step 2 try `snapper-rollback`

**Comment by jrabinow** [comment]
Thanks for the bugreport!

My system is offline at the moment so I won't be able to repro or debug, but let's see if I can't assist.

I don't see any breaking changes mentioned on [`btrfs-progs` homepage](https://btrfs.readthedocs.io/en/latest/CHANGES.html). Also, the project README [still mentions `btrfsutil` python module.](https://github.com/kdave/btrfs-progs/blob/fba31d634e3bc658e7d42a6c00f31ebb60adf901/libbtrfsutil/README.md?plain=1#L18)
Is there a way to confirm that the `btrfsutil` python module is installed from that package?

Further questions:
- what OS and version are you running? `cat /etc/os-release`
- what `btrfs-progs` package version are you coming from, and what is the new package version that doesn't work?
- any reason why `libopenmpt` and `libupnp` are relevant here?
- could you please share the output of `pacman -Ql btrfs-progs` ?
- what python version are you running, and what's the output of `python -c 'import sys;print(sys.path)'`?

**Comment by vuanhatran** [comment]
> Thanks for the bugreport!
> 
> My system is offline at the moment so I won't be able to repro or debug, but let's see if I can't assist.
> 
> I don't see any breaking changes mentioned on [`btrfs-progs` homepage](https://btrfs.readthedocs.io/en/latest/CHANGES.html). Also, the project README [still mentions `btrfsutil` python module.](https://github.com/kdave/btrfs-progs/blob/fba31d634e3bc658e7d42a6c00f31ebb60adf901/libbtrfsutil/README.md?plain=1#L18) Is there a way to confirm that the `btrfsutil` python module is installed from that package?
> 
> Further questions:
> 
> * what OS and version are you running? `cat /etc/os-release`
> * what `btrfs-progs` package version are you coming from, and what is the new package version that doesn't work?
> * any reason why `libopenmpt` and `libupnp` are relevant here?
> * could you please share the output of `pacman -Ql btrfs-progs` ?
> * what python version are you running, and what's the output of `python -c 'import sys;print(sys.path)'`?

Sorry was busy the whole day

- what OS and version are you running? cat /etc/os-release -->
`
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
`
- what btrfs-progs package version are you coming from, and what is the new package version that doesn't work? -->
`btrfs-progs-6.3-2 `
- any reason why libopenmpt and libupnp are relevant here? --> well, I don't know what they are but they get updated at the same time of btrfs-progs so I included them
- could you please share the output of pacman -Ql btrfs-progs ? -->
`pacman -Ql btrfs-progs
btrfs-progs /usr/
btrfs-progs /usr/bin/
btrfs-progs /usr/bin/btrfs
btrfs-progs /usr/bin/btrfs-convert
btrfs-progs /usr/bin/btrfs-find-root
btrfs-progs /usr/bin/btrfs-image
btrfs-progs /usr/bin/btrfs-map-logical
btrfs-progs /usr/bin/btrfs-select-super
btrfs-progs /usr/bin/btrfsck
btrfs-progs /usr/bin/btrfstune
btrfs-progs /usr/bin/fsck.btrfs
btrfs-progs /usr/bin/mkfs.btrfs
btrfs-progs /usr/include/
btrfs-progs /usr/include/btrfs/
btrfs-progs /usr/include/btrfs/ctree.h
btrfs-progs /usr/include/btrfs/ioctl.h
btrfs-progs /usr/include/btrfs/kerncompat.h
btrfs-progs /usr/include/btrfs/list.h
btrfs-progs /usr/include/btrfs/rbtree.h
btrfs-progs /usr/include/btrfs/rbtree_types.h
btrfs-progs /usr/include/btrfs/send-stream.h
btrfs-progs /usr/include/btrfs/send-utils.h
btrfs-progs /usr/include/btrfs/send.h
btrfs-progs /usr/include/btrfs/version.h
btrfs-progs /usr/include/btrfsutil.h
btrfs-progs /usr/lib/
btrfs-progs /usr/lib/initcpio/
btrfs-progs /usr/lib/initcpio/hooks/
btrfs-progs /usr/lib/initcpio/hooks/btrfs
btrfs-progs /usr/lib/initcpio/install/
btrfs-progs /usr/lib/initcpio/install/btrfs
btrfs-progs /usr/lib/libbtrfs.so
btrfs-progs /usr/lib/libbtrfs.so.0
btrfs-progs /usr/lib/libbtrfs.so.0.1
btrfs-progs /usr/lib/libbtrfsutil.so
btrfs-progs /usr/lib/libbtrfsutil.so.1
btrfs-progs /usr/lib/libbtrfsutil.so.1.2.0
btrfs-progs /usr/lib/pkgconfig/
btrfs-progs /usr/lib/pkgconfig/libbtrfsutil.pc
btrfs-progs /usr/lib/python3.11/
btrfs-progs /usr/lib/python3.11/site-packages/
btrfs-progs /usr/lib/python3.11/site-packages/btrfsutil-6.3-py3.11.egg-info/
btrfs-progs /usr/lib/python3.11/site-packages/btrfsutil-6.3-py3.11.egg-info/PKG-INFO
btrfs-progs /usr/lib/python3.11/site-packages/btrfsutil-6.3-py3.11.egg-info/SOURCES.txt
btrfs-progs /usr/lib/python3.11/site-packages/btrfsutil-6.3-py3.11.egg-info/dependency_links.txt
btrfs-progs /usr/lib/python3.11/site-packages/btrfsutil-6.3-py3.11.egg-info/top_level.txt
btrfs-progs /usr/lib/python3.11/site-packages/btrfsutil.cpython-311-x86_64-linux-gnu.so
btrfs-progs /usr/lib/systemd/
btrfs-progs /usr/lib/systemd/system/
btrfs-progs /usr/lib/systemd/system/btrfs-scrub@.service
btrfs-progs /usr/lib/systemd/system/btrfs-scrub@.timer
btrfs-progs /usr/lib/udev/
btrfs-progs /usr/lib/udev/rules.d/
btrfs-progs /usr/lib/udev/rules.d/64-btrfs-dm.rules
btrfs-progs /usr/lib/udev/rules.d/64-btrfs-zoned.rules
btrfs-progs /usr/share/
btrfs-progs /usr/share/bash-completion/
btrfs-progs /usr/share/bash-completion/completions/
btrfs-progs /usr/share/bash-completion/completions/btrfs
btrfs-progs /usr/share/man/
btrfs-progs /usr/share/man/man5/
btrfs-progs /usr/share/man/man5/btrfs.5.gz
btrfs-progs /usr/share/man/man8/
btrfs-progs /usr/share/man/man8/btrfs-balance.8.gz
btrfs-progs /usr/share/man/man8/btrfs-check.8.gz
btrfs-progs /usr/share/man/man8/btrfs-convert.8.gz
btrfs-progs /usr/share/man/man8/btrfs-device.8.gz
btrfs-progs /usr/share/man/man8/btrfs-filesystem.8.gz
btrfs-progs /usr/share/man/man8/btrfs-find-root.8.gz
btrfs-progs /usr/share/man/man8/btrfs-image.8.gz
btrfs-progs /usr/share/man/man8/btrfs-inspect-internal.8.gz
btrfs-progs /usr/share/man/man8/btrfs-map-logical.8.gz
btrfs-progs /usr/share/man/man8/btrfs-property.8.gz
btrfs-progs /usr/share/man/man8/btrfs-qgroup.8.gz
btrfs-progs /usr/share/man/man8/btrfs-quota.8.gz
btrfs-progs /usr/share/man/man8/btrfs-receive.8.gz
btrfs-progs /usr/share/man/man8/btrfs-replace.8.gz
btrfs-progs /usr/share/man/man8/btrfs-rescue.8.gz
btrfs-progs /usr/share/man/man8/btrfs-restore.8.gz
btrfs-progs /usr/share/man/man8/btrfs-scrub.8.gz
btrfs-progs /usr/share/man/man8/btrfs-select-super.8.gz
btrfs-progs /usr/share/man/man8/btrfs-send.8.gz
btrfs-progs /usr/share/man/man8/btrfs-subvolume.8.gz
btrfs-progs /usr/share/man/man8/btrfs.8.gz
btrfs-progs /usr/share/man/man8/btrfsck.8.gz
btrfs-progs /usr/share/man/man8/btrfstune.8.gz
btrfs-progs /usr/share/man/man8/fsck.btrfs.8.gz
btrfs-progs /usr/share/man/man8/mkfs.btrfs.8.gz
`
- what python version are you running, and what's the output of python -c 'import sys;print(sys.path)' -->
`python -c 'import sys;print(sys.path)'
['', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/usr/lib/python3.10/site-packages']
`

**Comment by jrabinow** [comment]
The problem here seems to be you're running python3.10 as your default version of python, but looking at the file listing for the package contents, `btrfs-progs` package is supplying only python3.11 code. I have to say I think it might be a bit unconventional that btrfs-progs only supports python3.11, but that's something either the package owner or the `btrfs-progs` people chose to do. It might be worth opening an issue with them about that.
I may also be wrong, pacman might try to do some "intelligent" dependency management based on currently installed python versions. You should be able to find this one out by checking if `python3.11` is installed on your system.

For a quick fix for your issue, you might consider doing one of the following:
- changing your default python version on your system to 3.11
- if that's not possible at this time, then I'd try to pin the btrfs-progs package to the previous version, until setting default python version to 3.11 became possible

**Comment by vuanhatran** [comment]
> The problem here seems to be you're running python3.10 as your default version of python, but looking at the file listing for the package contents, `btrfs-progs` package is supplying only python3.11 code. I have to say I think it might be a bit unconventional that btrfs-progs only supports python3.11, but that's something either the package owner or the `btrfs-progs` people chose to do. It might be worth opening an issue with them about that.
> I may also be wrong, pacman might try to do some "intelligent" dependency management based on currently installed python versions. You should be able to find this one out by checking if `python3.11` is installed on your system.
> 
> For a quick fix for your issue, you might consider doing one of the following:
> - changing your default python version on your system to 3.11
> - if that's not possible at this time, then I'd try to pin the btrfs-progs package to the previous version, until setting default python version to 3.11 became possible

Thank you, worked again after setting python default to 3.11

**Comment by jrabinow** [comment]
Closing the issue, glad to hear it's working
