### ISSUE TITLE
'mountpoint' value when running from installed system

### ISSUE THREAD

**Issue by gcala** [jrabinow/snapper-rollback#17]
Hi,
i'm playing with btrfs and snapshots from a VM before install in working machine.
I found your tool reading ArchWiki. After installing snapper-rollback from aur I opened the config file and I dunno how to set 'mountpoint'. In a live session probably it is /mnt but on real machine is just "/"?
In a running system do I have to set 'dev'?
Very tanks

**Comment by jrabinow** [comment]
- `dev` is the device file holding your btrfs toplevel, see the [flat layout](https://archive.kernel.org/oldwiki/btrfs.wiki.kernel.org/index.php/SysadminGuide.html#Flat)

- `mountpoint` is where `dev` will get mounted. See https://github.com/jrabinow/snapper-rollback/blob/47d9501e93d965019c92406600e6060c761c3f6e/snapper-rollback.conf#L24 This can be any directory of your choosing, but I'd recommend an empty directory. In particular, setting `mountpoint` as `/` sounds like a very bad idea unless you're looking for problems.

You don't have to set `dev` but in that case you should identify your btrfs toplevel and mount it yourself at `mountpoint` before running the script.

Apologies for the confusing terminology in the script, I need to standardize with the rest of the btrfs ecosystem. In any case, hopefully the above helps.

**Comment by jrabinow** [comment]
- `dev` is the device file holding your btrfs toplevel, see the [flat layout](https://archive.kernel.org/oldwiki/btrfs.wiki.kernel.org/index.php/SysadminGuide.html#Flat)

- `mountpoint` is where `dev` (your btrfs toplevel) will get mounted before performing the rollback. See https://github.com/jrabinow/snapper-rollback/blob/47d9501e93d965019c92406600e6060c761c3f6e/snapper-rollback.conf#L24 This can be any directory of your choosing, but I'd recommend an empty directory. In particular, setting `mountpoint` as `/` sounds like a very bad idea unless you're looking for problems.

You don't have to set `dev` but in that case you should identify your btrfs toplevel and mount it yourself at `mountpoint` before running the script.

Apologies for the confusing terminology in the script, I need to standardize with the rest of the btrfs ecosystem. In any case, hopefully the above helps.
