### ISSUE TITLE
Error on rollback

### ISSUE THREAD

**Issue by somesmart** [jrabinow/snapper-rollback#18]
I'm getting the follow error when trying to rollback: 

`ERROR - [BtrfsUtilError 7 Errno 2] Could not open: No such file or directory: '/btrfsroot/@.snapshots/29/snapshot' -> '/btrfsroot/@'`

I can see my snapshots with snapper ls and I can see them in the /.snapshots directory. I'm guessing it might be related to this comment from the readme: 

"Edit /etc/snapper-rollback.conf and make sure all the settings have the right values. You don't have to do this, but if you don't, you'll have to manually mount your btrfs root subvolume to /btrfsroot before running the script."

Did I miss a step somewhere?

Edit: sorry I didn't mean to mark this a bug as I'm certain I did something wrong.

**Comment by jrabinow** [comment]
Hi @somesmart 

Did you remember to mount your btrfs root to the `/btrfsroot` directory?
I recommend editing `/etc/snapper-rollback.conf` per the README, you should find some explanations in there.

**Comment by somesmart** [comment]
I updated my `/etc/snapper-rollback.conf` as below:

```
# config for btrfs root
[root]
# Name of your linux root subvolume
subvol_main = @
# Name of your snapper snapshot subvolume
subvol_snapshots = @.snapshots
# Directory to which your btrfs root is mounted.
mountpoint = /btrfsroot
# Device file for btrfs root.
# If your btrfs root isn't mounted to `mountpoint` directory, then automatically
# mount this device there before rolling back. This parameter is optional, but
# if unset, you'll have to mount your btrfs root manually.
dev = /dev/nvme0n1p2
```

but if I need to mount my btrfs root to the `/btrfsroot` elsewhere I'm not sure I understood. Sorry if this is a newbie issue, still new to btrfs and arch linux!

**Comment by jrabinow** [comment]
If you've configured your `snapper-rollback.conf` with the proper values per the comments, you should be all set. No worries :-)
It does sound like you have a goal in mind and are trying to guess how to achieve it. My advice is to take the time to dig and read into what it is you're trying to achieve, especially if you're starting out. It may be slower today but when (not if) things break one day, you'll already know exactly how things are built.

In this particular case, I feel like you're interested in building a mental model of how this script works. Can I suggest taking a moment and reading through the code? There's no need to do this usually, but I think setting aside some time to do so will give you much firmer footing as to the answers you're looking for.

I will say though, reading the code should be unnecessary, it seems you already figured out the right setup on your own.

**Comment by somesmart** [comment]
Thank you, I appreciate the courteous words and good advice. I'll do some more reading and figure out what I've missed!

**Comment by somesmart** [comment]
Just for posterity's sake if anyone else searches for this same issue, I needed to edit  /etc/btrfs-assistant.conf to map the subvolume to the snapshot directory

`root = "@snapshots,@,UUID"`

**Comment by jrabinow** [comment]
Thanks for reporting back with the solution!
