### ISSUE TITLE
[FEATURE] delete /var/lib/pacman/db.lck

### ISSUE THREAD

**Issue by sanmue** [jrabinow/snapper-rollback#21]
**Is your feature request related to a problem? Please describe.**
When I wanna do a system update or install new software after a rollback, i get every time:
`error: failed to synchronize all databases (unable to lock database)`

This can be solved, according to the [corresponding pacman troubleshooting section](https://wiki.archlinux.org/title/Pacman#%22Failed_to_init_transaction_(unable_to_lock_database)%22_error) with:
`# rm /var/lib/pacman/db.lck`

**Describe the solution you'd like**
Perhaps this can be done in your script too, if this lock file exists in the snapshot to be restored.

**Describe alternatives you've considered**
Well, if you use Arch you should know how to read the wiki. So it is not necessary, just a convenience thing.

**Additional context**
none

**Comment by jrabinow** [comment]
I think you may be rolling back to a snapshot which had a pacman problem. I'll suggest deleting the problematic file, taking a new snapshot and rolling back to the new snapshot going forward.

Handling locks for external programs, or any other application-specific behavior, is out of scope for this script. It's possible to do these things but it would add great amounts of complexity to a script which is meant to be reliable and work in all cases.

Feel free to fork and adapt the code to your personal needs if you'd like!
