### ISSUE TITLE
Snapshot not restored despite success message

### ISSUE THREAD

**Issue by david-cortes** [jrabinow/snapper-rollback#8]
I'm trying to set up a debian system with a similar snapper rollback option in GRUB as opensuse and spiral linux do, by using snapshots from [grub-btrfs](https://github.com/Antynea/grub-btrfs).

When I try to execute `snapper-rollback`, whether from the mainline root subvolume or from a bootable snapshot, I get a "success" message, but the snapshot is not restored next time I boot into my main system.

```
david@debian:~$ sudo snapper-rollback 69
Are you SURE you want to rollback? Type 'CONFIRM' to continue: CONFIRM
2023-03-03 13:59:25,716 - INFO - FalseRollback to /btrfsroot/snapshots/69/snapshot complete. Reboot to finish
```

Some help would be appreciated here

****************************
Info:

* `/etc/fstab`:
```
UUID=a90b4fdd-ead4-4100-9ca8-509cdf3597b4 /               btrfs   defaults,autodefrag,compress=zstd,subvol=@ 0       0
UUID=CAED-898F  /boot/efi       vfat    umask=0077      0       1
UUID=b3561c81-1ce5-4c8e-95b9-119b61bf698a /home           btrfs   defaults        0       0
UUID=eca8bd39-7cb6-4043-b95c-44f6d25dc67e /tmp            ext4    defaults        0       2
UUID=45239f15-e700-460f-9686-345c622c2df1 /var            ext4    defaults        0       2
UUID=18143a4f-3cd5-4cf9-93d9-cd8a38442ff9 none            swap    sw              0       0
/dev/nvme0n1p2 /.snapshots btrfs defaults,autodefrag,compress=zstd,commit=120,noatime,subvol=snapshots 0 0
/dev/nvme0n1p2 /btrfsroot btrfs defaults,subvolid=5 0 0
```

* `sudo btrfs subvol list /` (minus a long list of irrelevant snapshots) after executing `snapper-rollback`:
```
ID 256 gen 255 top level 5 path @rootfs
ID 257 gen 254 top level 5 path snapshots
ID 259 gen 61 top level 257 path snapshots/1/snapshot
...
ID 303 gen 213 top level 5 path @2023-03-03T13:21
ID 328 gen 248 top level 257 path snapshots/69/snapshot
ID 329 gen 218 top level 257 path snapshots/70/snapshot
...
ID 338 gen 242 top level 5 path @2023-03-03T13:56
ID 339 gen 247 top level 257 path snapshots/76/snapshot
ID 340 gen 248 top level 5 path @
ID 341 gen 252 top level 257 path snapshots/77/snapshot
```

* `snapper-rollback.conf` changes:
```
[root]
subvol_main = @
subvol_snapshots = snapshots
mountpoint = /btrfsroot
dev = /dev/nvme0n1p2
```

**Comment by jrabinow** [comment]
Hmm, I see nothing here looks wrong to my non-expert eyes. but let's try to narrow down the issue:

- this one is obvious but let's check just in case. Your `/` and `/home` are btrfs, but `/var` and `/tmp` are ext4. `/` will roll back, but `/var` and `/tmp` won't - I'm assuming you aren't assuming they rollback, right? Just double-checking.

- what's the UUID for `/dev/nvme0n1p2`? It should be the same as your root partition. `ls -l /dev/disk/by-uuid`

- you opened a PR that suggests you ran into a BTRFS issue (thanks for contributing back btw!). This makes me wonder whether your system is currently in a consistent state. Did you record the exception, and if so what does it say? What's the current default btrfs subvolume? 

- let's rule out that this is grub booting into the wrong subvolume. When you try to boot into the system after running snapper-rollback, what menuentry are you selecting from grub? How is that menuentry configured? (Most likely under `/boot/grub/grub.cfg`)

- The script has a `--dry-run` mode which will output a few shell commands. If you run the commands directly, are there any errors anywhere?

**Comment by david-cortes** [comment]
Thanks for your help. So from these checks I figured out it was an issue with the grub config booting from `@rootfs` instead of `@`, despite `@` being the default subvolume.

It worked fine after changing the config to `subvol_main = @rootfs`.

**Comment by jrabinow** [comment]
Thanks for reporting back with the resolution.

Ideally, this situation wouldn't happen at all to begin with - can I ask how are you generating your `grub.cfg`? I'm thinking that we should take steps to avoid the next person running into the same issue -> if re-running `update-grub` doesn't generate the correct menuentry, it might be worth checking with the grub people whether it'd make sense to add that kind of auto-detection.

**Comment by david-cortes** [comment]
I am not familiar with how grub works in this context. `@rootfs` is what the debian installer creates when formatting a btrfs partition that is set as `/`, whereas `@` is what I had created manually through `btrfs` commands while trying to follow the arch wiki.

The `grub.cfg` that I had was also the default that's auto-generated by debian. `update-grub` doesn't change it to point to `@` instead of `@rootfs` if I manually play with `btrfs subvol` and set it as default.

**Comment by jrabinow** [comment]
Got it, so in that case, this sounds like different conventions across linux distros: `@` for archlinux, `@rootfs` for Debian. Next week, I'll update the repo readme so that it flags this potential discrepancy.
